# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QErUZiSleSIddNrPbSEv0Z0Otcw85ja2
"""

pip install jqdatasdk

import jqdatasdk as jq
jq.auth("15850683986","19980306zxyYU")

import pandas as pd
import numpy as np
import time
import datetime

minu_datas = pd.DataFrame()
series = jq.get_dominant_future('IF','2013-01-01','2022-03-30')

for time1 in series.index:
  future = series.loc[time1]
  time1 = pd.Timestamp(time1)

  panel=jq.get_price(future,frequency='minute',start_date=pd.Timestamp.combine(time1,datetime.time(9,30,0)), end_date=pd.Timestamp.combine(time1,datetime.time(15,0,0)), fields=['open', 'close', 'low', 'high', 'volume', 'money','pre_close'])
  panel['code'] = future
  minu_datas = minu_datas.append(panel)
minu_datas.to_csv('minu_datas.csv',index=True)