# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QErUZiSleSIddNrPbSEv0Z0Otcw85ja2
"""

pip install jqdatasdk

import jqdatasdk as jq
jq.auth("15850683986","19980306zxyYU")

import pandas as pd
import numpy as np
import time

def select_futures(datas,time1,name):
  stock_futures = pd.DataFrame()
  
  for ind in datas.index.tolist():

      if ind[:2] == name and datas.loc[ind,'end_date'].timestamp()>=time1 and ind[2:6] != '8888' and ind[2:6] != '9999':
          
          stock_futures = stock_futures.append(datas.loc[ind])
  return stock_futures

def main_futures(stock_futures):
    temp = {}
    main_seq = pd.DataFrame()
    
    for future in stock_futures.index.tolist():
        panel= jq.get_price(future,frequency='minute',start_date='2013-01-01 9:30:00', end_date='2022-03-30 15:00:00', fields=['open', 'close', 'low', 'high', 'volume', 'money'])
        temp[future] = panel
    
    for ind in panel.index.tolist():
        temp_volume , res = 0,0
        for future in stock_futures.index.tolist():
            if temp[future].loc[ind,'volume']>temp_volume:
                temp_volume = temp[future].loc[ind,'volume']
                res = future
        series = pd.DataFrame({'code':res ,'volume':temp_volume} ,index =[ind])
        main_seq = main_seq.append(series)
    return main_seq

def main():
    datas = jq.get_all_securities(['futures'])
    name = 'IF'
    time1 = time.mktime(time.strptime("2013-01-01 00:00:00","%Y-%m-%d %H:%M:%S"))
    
    stock_futures = select_futures(datas,time1,name)
 
    res = main_futures(stock_futures)
    res.to_csv('res.csv', index=True)

main()