# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QErUZiSleSIddNrPbSEv0Z0Otcw85ja2
"""

pip install jqdatasdk

import jqdatasdk as jq
jq.auth("15850683986","19980306zxyYU")

import pandas as pd
import numpy as np
import time

def select_futures(now_time,name):
  stock_futures = pd.DataFrame()
  
  for ind in datas.index.tolist():

      if ind[:2] == name and datas.loc[ind,'end_date']>=now_time>=datas.loc[ind,'start_date'] and ind[2:6] != '8888' and ind[2:6] != '9999':
          
          stock_futures = stock_futures.append(datas.loc[ind])
  return stock_futures

def main_futures(start_date,end_date,stock_futures):
    temp = {}
    main_seq = pd.DataFrame()
    
    for future in stock_futures.index.tolist():
        panel= jq.get_price(future, start_date=start_date,end_date=end_date, frequency='minute', fields=['volume'])
        temp[future] = panel
    
    for ind in panel.index.tolist():
       
        temp_volume , res = 0,0
        for future in stock_futures.index.tolist():
            if temp[future].loc[ind,'volume']>temp_volume:
                temp_volume = temp[future].loc[ind,'volume']
                res = future
        series = pd.DataFrame({'code':res ,'volume':temp_volume} ,index =[ind])
        main_seq = main_seq.append(series)
    return main_seq

def main():
    datas = jq.get_all_securities(['futures'])
    name = 'IF'
  
    
    now_time = pd.datetime.now()
    stock_futures = select_futures(now_time,name)
 
    res = main_futures('2022-03-28 9:30:00','2022-03-28 9:45:00',stock_futures)
    print(res)

main()